stable:
  impl: geth
  repo: ethereum/go-ethereum
  ref: master
develop:
  impl: geth
  repo: lightclient/go-ethereum
  ref: prague-devnet-1
eip7692:
  impl: evmone
  repo: ethereum/evmone
  ref: master
eip7692-prague:
  impl: besu
  repo: hyperledger/besu
  ref: main
  evm-bin: evmone-t8n
verkle:
  impl: geth
  repo: gballet/go-ethereum
  ref: kaustinen-with-shapella
  evm-bin: evm
