stable:
  impl: eels
  repo: null
  ref: null
develop:
  impl: eels
  repo: null
  ref: null
static:
  impl: evmone
  repo: ethereum/evmone
  ref: master
  targets: ["evmone-t8n", "evmone-eofparse"]
zkevm:
  impl: eels
  repo: null
  ref: null
eip7692:
  impl: evmone
  repo: ethereum/evmone
  ref: master
  targets: ["evmone-t8n", "evmone-eofparse"]