legacy:
  evm-type: stable
  fill-params: --until=Shanghai
  solc: 0.8.21
stable:
  evm-type: stable
  fill-params: --fork=Cancun
  solc: 0.8.21
develop:
  evm-type: develop
  fill-params: --from=Cancun --until=Prague
  solc: 0.8.21
eip7692:
  evm-type: eip7692
  fill-params: --fork=Osaka ./tests/osaka
  solc: 0.8.21
  eofwrap: true
eip7692-osaka:
  evm-type: eip7692-osaka
  fill-params: --fork=Osaka ./tests/prague ./tests/osaka -k "not slow"
  solc: 0.8.21
pectra-devnet-3:
  evm-type: pectra-devnet-3
  fill-params: --fork=Prague -m "not slow" ./tests/prague/
  solc: 0.8.21
pectra-devnet-4:
  evm-type: pectra-devnet-4
  fill-params: --fork=Prague -m "not slow and not eip_version_check" ./tests/prague/
  solc: 0.8.21