# Unless filling for special features, all features should fill for previous forks (starting from Frontier) too
stable:
  evm-type: stable
  fill-params: --until=Cancun
  solc: 0.8.21
develop:
  evm-type: develop
  fill-params: --until=Prague
  solc: 0.8.21
eip7692:
  evm-type: eip7692
  fill-params: --fork=Osaka ./tests/osaka
  solc: 0.8.21
  eofwrap: true
