name: Deploy Docs Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.repository_owner == 'ethereum' # don't run on forks
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{secrets.GH_ACTIONS_DEPLOY_KEY}}
      - name: Build transition tool
        uses: ./.github/actions/build-evm-base
        with:
          id: evm-builder
          type: stable
      - name: Set up uv
        uses: ./.github/actions/setup-uv
      - name: Set up Python
        run: uv python install 3.11
      - name: Install EEST and dependencies
        run: uv sync --extra=docs --no-progress
      - name: Setup doc deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email github-actions[bot]@users.noreply.github.com
      - name: Build and deploy docs to gh-pages
        run: |
          uv run mike deploy --update-aliases --push --remote origin main development
