name: Build and Package Fixtures for a feature

on:
  push:
    tags:
      - "*@v*"
  workflow_dispatch:

jobs:
  feature-names:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.feature-name.outputs.names }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: false
      - name: Get feature names
        id: feature-name
        shell: bash
        run: |
          names=$(grep -Po "^${GITHUB_REF_NAME//@*/}[^:]*" .github/configs/feature.yaml | jq  --raw-input .  | jq -c --slurp .)
          echo names=${names}
          echo names=${names} >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: feature-names
    strategy:
      matrix:
        feature: ${{ fromJSON(needs.feature-names.outputs.names) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: true
      - uses: ./.github/actions/build-fixtures
        with:
          release_name: ${{ matrix.feature }}
          uv_version: ${{ vars.UV_VERSION }}
          python_version: ${{ vars.DEFAULT_PYTHON_VERSION }}
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          path: .
      - name: Draft Pre-release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: "./**"
          draft: true
          prerelease: true
          generate_release_notes: true
          fail_on_unmatched_files: true
