name: Build and Package Fixtures for a feature

on:
  push:
    tags:
      - "*@v*"
  workflow_dispatch:

jobs:
  feature-names:
    runs-on: ubuntu-24.04
    outputs:
      names: ${{ steps.feature-name.outputs.names }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Get feature names
        id: feature-name
        shell: bash
        run: |
          names=$(grep -Po "^${GITHUB_REF_NAME//@*/}[^:]*" .github/configs/feature.yaml | jq  --raw-input .  | jq -c --slurp .)
          echo names=${names}
          echo names=${names} >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-24.04
    needs: feature-names
    strategy:
      matrix:
        feature: ${{ fromJSON(needs.feature-names.outputs.names) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/build-fixtures
        with:
          release_name: ${{ matrix.feature }}
  release:
    runs-on: ubuntu-24.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Draft Pre-release
        uses: softprops/action-gh-release@v2
        with:
          files: "./**"
          draft: true
          prerelease: true
          generate_release_notes: true
          fail_on_unmatched_files: true
